function [tout, yout] = run_steamcondenser(u)
    assignin('base','u',u);
    assignin('base','ST',u(length(u))); % Note: variable T used by the model
    
    result = sim('steamcondense_RNN_22', ...
        'StopTime', 'ST', ...
        'LoadExternalInput', 'on', 'ExternalInput', 'u', ...
        'SaveTime', 'on', 'TimeSaveName', 'tout', ...
        'SaveOutput', 'on', 'OutputSaveName', 'yout', ...
        'SaveFormat', 'Array');
    tout = result.tout;
    yout = result.yout;
end
